version: '3'
services:
  be:
    build: ./BE/zeepseek
    container_name: backend_container
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  fe:
    build: ./FE
    container_name: frontend_container
    ports:
      - "3000:3000"
    restart: always

  recommend:
    build: ./ML
    container_name: recommend_container
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MONGO_HOST=host.docker.internal
      - ES_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always