recommendation:
  api:
    host: http://localhost  # 로컬 환경
    port: 8000              # FastAPI 서비스 포트

logging:
  level:
    com.zeepseek.backend.domain.recommend: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
